run command, changes adapted for cpcemu and rvm

diff --git a/bin/run b/bin/run
--- a/bin/run
+++ b/bin/run
@@ -28,6 +28,8 @@
 
 ## Bash Include files
 source $(dirname "$0")/lib/library.sh
+# Allowed values for the emulator parameter
+emulators=("m4" "rvm")
 
 # Function to display help message
 function show_help {
@@ -36,25 +38,29 @@ function show_help {
     echo "Run Files in Emulator"
     echo 
     echo "Use: $(basename "$0") [option]"
+    echo "  -e, --emulator Emulator type [M4, RVM]"
+    echo "  -d, --dsk      Disk image name."
     echo "  -h, --help     Show this help message."
     echo "  -v, --version  Show version this software."
     echo "Option:"
-    echo "  [parameter]  [M4, RVM]"
+    echo "  [parameter]  --emulator [M4, RVM]"
+    echo "               --dsk "
+    echo "               If no default parameters are passed, the values ​"
+    echo "               ​of the EMULATOR and DISC environment variables are taken."
     ready
 }
 
-# Check if the help parameter is provided
-case $1 in
-    -v|--version)
-        show_version
-        ready
-        exit 0
-        ;;
-    -h|--help)
-        show_help
-        exit 0
-        ;;
-esac
+# Function to check if a value is in a list
+isEmulator() {
+    local value="$1"
+    value=$(echo "$1" | tr '[:upper:]' '[:lower:]')
+    export $EMULATOR="$value"
+    shift
+    for element; do
+        [[ "$element" == "$value" ]] && return 0
+    done
+    return 1
+}
 
 ## Chequeamos si existe el archivo de variables.
 ## si no existe salimos con error
@@ -66,6 +72,52 @@ source "$PATH_CONFIG_PROJECT/$CONFIG_CPCREADY"
 ## Show logo
 CPCREADY
 
+
+if [[ -z "$EMULATOR" ]]; then
+    export EMULATOR="rvm"
+fi
+
+
+# Default values
+
+EMULATOR="$EMULATOR"
+DSK="$DISC"
+
+# Check if the help parameter is provided
+# Process command line options
+while [[ "$#" -gt 0 ]]; do
+    case "$1" in
+        -v|--version)
+            show_version
+            ready
+            exit 0
+            ;;
+        -h|--help)
+            show_help
+            exit 0
+            ;;
+        -e|--emulator)
+            if [[ -z "$2" ]]; then
+                PRINT "ERROR" "Missing argument for option $1" >&2
+            fi
+            if ! isEmulator "$2" "${emulators[@]}"; then
+                PRINT "ERROR" "The emulator value must be one of ${emulators[*]}" >&2
+            fi
+            value=$(echo "$2" | tr '[:upper:]' '[:lower:]')
+            EMULATOR="$value"
+            shift 2
+            ;;
+        -d|--dsk)
+            if [[ -z "$2" ]]; then
+                PRINT "ERROR" "Missing argument for option $1" >&2
+            fi
+            DSK="$2"
+            shift 2
+            ;;
+        *) echo "Invalid option: $1" >&2; exit 1 ;;
+    esac
+done
+
 if [[ "$OSTYPE" == "linux-gnu" ]]; then
     CPCEMU="$CPCREADY/bin/linux/cpcemu/cpcemu"
     RVM="$CPCREADY/bin/linux/cpcemu/cpcemu"
@@ -76,38 +128,27 @@ else
     PRINT ERROR "$OSTYPE Operating system NOT supported."
 fi
 
-# Convertir el valor de $1 a minúsculas
-param=$(echo "$1" | tr '[:upper:]' '[:lower:]')
-
-# comprobamos si se pasa parametro 2 que es la imagen de disco
-# si no se pasa se coge por defecto la variable $DISC
-if [ -n "$2" ]; then
-    IMAGE="$2"
-else
-    IMAGE="$DISC"
-fi
-
 # Comprobar si el valor es "m4" o "rvm"
-if [[ "$param" == "m4" || "$param" == "rvm" ]]; then
+# if [[ "$EMULATOR" == "m4" || "$EMULATOR" == "rvm" ]]; then
     # Realizar acciones específicas para "m4" y "disc"
-    if [[ "$param" == "m4" ]]; then
-        model_cpc m4$MODEL
-        PRINT "OK" "Emulator: CPCEmu."
-        PRINT "OK" "Project execute in SD."
-        $CPCEMU -f -c "$PWD/$PATH_CONFIG_PROJECT/$CONFIG_CPCEMU" > /dev/null 2>&1 &
-    elif [[ "$param" == "rvm" ]]; then
-        if [ ! -e "$OUT_DISC/$IMAGE" ]; then
-            PRINT "ERROR" "$OUT_DISC/$IMAGE not found."
-        fi
-        model_cpc $MODEL
-        PRINT "OK" "Emulator: RetroVirtualMachine."
-        PRINT "OK" "DISC: $DISC"
-        PRINT "OK" "run\"disc.bas"
-        $RVM -b=cpc$MODEL -i "$OUT_DISC/$IMAGE" -c='run"disc\n' > /dev/null 2>&1 &
-    fi    
-else
-   echo
-   PRINT "ERROR" "Bad command"
-fi
+if [[ "$EMULATOR" == "m4" ]]; then
+    model_cpc m4$MODEL
+    PRINT "OK" "Emulator: CPCEmu."
+    PRINT "OK" "Project execute in SD."
+    $CPCEMU -f -c "$PWD/$PATH_CONFIG_PROJECT/$CONFIG_CPCEMU" > /dev/null 2>&1 &
+elif [[ "$EMULATOR" == "rvm" ]]; then
+    if [ ! -e "$OUT_DISC/$DSK" ]; then
+        PRINT "ERROR" "$OUT_DISC/$DSK not found."
+    fi
+    model_cpc $MODEL
+    PRINT "OK" "Emulator: RetroVirtualMachine."
+    PRINT "OK" "DISC: $DISC"
+    PRINT "OK" "run\"disc.bas"
+    $RVM -b=cpc$MODEL -i "$OUT_DISC/$DSK" -c='run"disc\n' > /dev/null 2>&1 &
+fi    
+# else
+#    echo
+#    PRINT "ERROR" "Bad command"
+# fi
 
 ready
